config/routes.rb
Joe::Application.routes.draw do
  resources :ihateerbs

  resource :desktop do
  end

  resources :words do
  end	   

end

app/models/ihateerb.rb
class Ihateerb < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/desktops_controller.rb
class DesktopsController < ApplicationController

    def show
      render :inline =>"<div id='desktop'></div>", :layout => true
	  end
end

app/controllers/ihateerbs_controller.rb
class IhateerbsController < ApplicationController
  # GET /ihateerbs
  # GET /ihateerbs.json
  def index
    @ihateerbs = Ihateerb.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ihateerbs }
    end
  end

  # GET /ihateerbs/1
  # GET /ihateerbs/1.json
  def show
    @ihateerb = Ihateerb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ihateerb }
    end
  end

  # GET /ihateerbs/new
  # GET /ihateerbs/new.json
  def new
    @ihateerb = Ihateerb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ihateerb }
    end
  end

  # GET /ihateerbs/1/edit
  def edit
    @ihateerb = Ihateerb.find(params[:id])
  end

  # POST /ihateerbs
  # POST /ihateerbs.json
  def create
    @ihateerb = Ihateerb.new(params[:ihateerb])

    respond_to do |format|
      if @ihateerb.save
        format.html { redirect_to @ihateerb, :notice => 'Ihateerb was successfully created.' }
        format.json { render :json => @ihateerb, :status => :created, :location => @ihateerb }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ihateerb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ihateerbs/1
  # PUT /ihateerbs/1.json
  def update
    @ihateerb = Ihateerb.find(params[:id])

    respond_to do |format|
      if @ihateerb.update_attributes(params[:ihateerb])
        format.html { redirect_to @ihateerb, :notice => 'Ihateerb was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ihateerb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ihateerbs/1
  # DELETE /ihateerbs/1.json
  def destroy
    @ihateerb = Ihateerb.find(params[:id])
    @ihateerb.destroy

    respond_to do |format|
      format.html { redirect_to ihateerbs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/system_info_controller.rb
class SystemInfoController < ApplicationController
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  # Returns a random word
  def index
    @words = []
    File.open("/usr/share/dict/words") do |io|
	    line_count = 0
  	  io.each do |line|
  	    line_count += 1
  	    @words << line
  	  end
    end
    respond_to { |format|
      format.json { render :json => [@words[rand @words.size]]}
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ihateerbs_helper.rb
module IhateerbsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/ihateerbs/_form.html.erb
<%= form_for(@ihateerb) do |f| %>
  <% if @ihateerb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ihateerb.errors.count, "error") %> prohibited this ihateerb from being saved:</h2>

      <ul>
      <% @ihateerb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ihateerbs/edit.html.erb
<h1>Editing ihateerb</h1>

<%= render 'form' %>

<%= link_to 'Show', @ihateerb %> |
<%= link_to 'Back', ihateerbs_path %>

app/views/ihateerbs/index.html.erb
<h1>Listing ihateerbs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ihateerbs.each do |ihateerb| %>
  <tr>
    <td><%= link_to 'Show', ihateerb %></td>
    <td><%= link_to 'Edit', edit_ihateerb_path(ihateerb) %></td>
    <td><%= link_to 'Destroy', ihateerb, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ihateerb', new_ihateerb_path %>

app/views/ihateerbs/new.html.erb
<h1>New ihateerb</h1>

<%= render 'form' %>

<%= link_to 'Back', ihateerbs_path %>

app/views/ihateerbs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_ihateerb_path(@ihateerb) %> |
<%= link_to 'Back', ihateerbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name = "viewport" content = "width = device-width, height = 100, user-scalable = no, maximum-scale=1.0">
  
  <title>Joe</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/show.html.haml
#desktop